defaults:
  -
    scope:
      path: ""
    values:
      layout: page

title: "syn·di·cate"
subtitle: "a language for interactive programs"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
